apiVersion: v1
kind: pod
metadata:
  name: worker-app
  labels:
    name: worker-app
    app: demo-voting-app

  spec:
    containers:
      - name: worker-app
        image: dockersamples/examplevotingapp_worker
